default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['TASKS_DATABASE_USER'] %>
  password: <%= ENV['TASKS_DATABASE_PASSWORD'] %>
  host: <%= ENV['TASKS_DATABASE_HOST'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tasks_development

test:
  <<: *default
  database: tasks_test

production:
  <<: *default
  database: tasks_production

